### ISSUE TITLE
Enhancement to print completion time for each operation

### ISSUE THREAD

**Issue by paregupt** [HabanaAI/hccl_demo#35]
Is it possible to enhance the data_csv file to print only the completion time for that buffer transfer? 

This will help to benchmark network optimization features by measuring tail latency. For example, with loop 100000, I am looking for a way to get those many completion time values and then compare them when different features are enabled on the network.

While looking at the code, I am wondering if taking time difference before and after calling fn would give the completion time, but just want to be sure that this won't cause any side effects.
```
    for (size_t iter = 1; iter < demo_data.num_iters; ++iter)
    {
        fn(iter);
    }
``` 
Thank you.

**Comment by ytava** [comment]
Hi,

The short answer is that you won't get accurate time measurement.
Time measurement/capture is taken on the host, while the operation is being executed on the Gaudi device. If running a single iteration, which is executed in a very short duration, the overhead of synching it with the host and sampling the host clock is longer than its execution time and won't reflect accurate duration of the device execution time of "fn". When running many iterations, the measurement overhead is averaged and it's affect is negligible.

Not sure if this could help, but for example you can run 10K iterations and measure on each 1K group. Still you will need to add synEventRecord after iteration 1000 and sync on that event on the host with synEventSyncronize (so you could take time capture after iteration 1000 was executed and not after it got submitted).

Thanks,
Ytav.

**Comment by paregupt** [comment]
Hi Ytav, thanks for taking the time to explain this. I see your point. BTW, I am using 200,000 loop value to compare the results of various scenarios with an assumption that this would minimize the overhead. 
Thanks again, please feel free to close this issue.
